version: "3.8"

services:
  backend:
    build: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      - DB_HOST=db
      - DB_NAME=netflix_clone
      - DB_USER=netflix_user
      - DB_PASSWORD=securepass
      - REDIS_HOST=redis

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: netflix_clone
      MYSQL_USER: netflix_user
      MYSQL_PASSWORD: securepass
      MYSQL_ROOT_PASSWORD: rootpass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  redis:
    image: redis:6.2
    restart: always
    ports:
      - "6379:6379"

  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./frontend:/usr/share/nginx/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./backend/media:/app/media
    depends_on:
      - backend

volumes:
  db_data:
  
