# Generated by Django 5.2.5 on 2025-08-20 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video_app', '0003_video_created_at_video_hls_path_alter_video_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='entitlement',
        ),
        migrations.RemoveField(
            model_name='video',
            name='price',
        ),
    ]
